/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountIdentifier = Uint8Array;
export type ActiveListing = { 'Fixed' : FixedListing } |
  { 'Auction' : AuctionListing };
export interface AuctionListing {
  'id' : ListingId,
  'status' : ListingStatus,
  'highestBidder' : [] | [UserId],
  'endTime' : Timestamp,
  'createdAt' : Timestamp,
  'seller' : UserId,
  'highestBid' : bigint,
  'nftId' : NFTId,
  'startingBid' : bigint,
}
export interface Collection {
  'id' : CollectionId,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'standard' : NFTStandard,
  'symbol' : string,
  'canisterId' : Principal,
}
export type CollectionId = bigint;
export interface FixedListing {
  'id' : ListingId,
  'status' : ListingStatus,
  'createdAt' : Timestamp,
  'seller' : UserId,
  'nftId' : NFTId,
  'price' : bigint,
}
export type ListingId = bigint;
export type ListingStatus = { 'Sold' : null } |
  { 'Active' : null } |
  { 'Cancelled' : null } |
  { 'Settled' : null };
export type NFTId = bigint;
export interface NFTMetadata {
  'name' : [] | [string],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
  'attributes' : Array<[string, string]>,
}
export type NFTStandard = { 'EXT' : null } |
  { 'DIP721' : null } |
  { 'Other' : string };
export interface NFTStats {
  'totalCount' : bigint,
  'perCollection' : Array<[CollectionId, bigint]>,
}
export type Timestamp = bigint;
export interface Tokens { 'e8s' : bigint }
export type TransferError = {
    'TxTooOld' : { 'allowed_window_nanos' : bigint }
  } |
  { 'BadFee' : { 'expected_fee' : Tokens } } |
  { 'TxDuplicate' : { 'duplicate_of' : bigint } } |
  { 'TxCreatedInFuture' : null } |
  { 'InsufficientFunds' : { 'balance' : Tokens } };
export type TransferResult = { 'Ok' : bigint } |
  { 'Err' : TransferError };
export type UserId = Principal;
export interface WalletNFT {
  'id' : NFTId,
  'tokenId' : string,
  'collectionId' : CollectionId,
  'owner' : UserId,
  'metadata' : NFTMetadata,
  'registeredAt' : Timestamp,
}
export interface _SERVICE {
  'addCollection' : ActorMethod<
    [string, string, Principal, NFTStandard, string, string],
    Collection
  >,
  'bootstrapAdmin' : ActorMethod<[], undefined>,
  'buyFixedListing' : ActorMethod<[ListingId], undefined>,
  'cancelListing' : ActorMethod<[ListingId], undefined>,
  'createAuctionListing' : ActorMethod<[NFTId, bigint, bigint], AuctionListing>,
  'createFixedListing' : ActorMethod<[NFTId, bigint], FixedListing>,
  'getActiveListings' : ActorMethod<[], Array<ActiveListing>>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getCollection' : ActorMethod<[CollectionId], [] | [Collection]>,
  'getCollectionNFT' : ActorMethod<[CollectionId, string], [] | [WalletNFT]>,
  'getCollectionNFTs' : ActorMethod<[CollectionId], Array<WalletNFT>>,
  'getNFTStats' : ActorMethod<[Principal], NFTStats>,
  'getUserAccountId' : ActorMethod<[], AccountIdentifier>,
  'getUserICPBalance' : ActorMethod<[], bigint>,
  'getUserNFTs' : ActorMethod<[Principal], Array<WalletNFT>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isNFTInUserWallet' : ActorMethod<[CollectionId, string, UserId], boolean>,
  'listCollections' : ActorMethod<[], Array<Collection>>,
  'placeBid' : ActorMethod<[ListingId, bigint], AuctionListing>,
  'registerNFT' : ActorMethod<
    [CollectionId, string, NFTMetadata],
    { 'ok' : WalletNFT } |
      { 'err' : string }
  >,
  'removeCollection' : ActorMethod<[CollectionId], boolean>,
  'sendNFT' : ActorMethod<
    [NFTId, Principal],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'settleAuction' : ActorMethod<[ListingId], undefined>,
  'syncUserNFTs' : ActorMethod<
    [],
    { 'ok' : { 'errors' : Array<string>, 'newCount' : bigint } } |
      { 'err' : string }
  >,
  'transferICPOut' : ActorMethod<[AccountIdentifier, bigint], TransferResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];